<?php

namespace MainBundle\Entity;

/**
 * HomeSkillsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomeSkillsRepository extends \Doctrine\ORM\EntityRepository
{
}
