<?php

namespace MainBundle\Entity;

/**
 * ResponsibilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsibilityRepository extends \Doctrine\ORM\EntityRepository
{
}
